### ISSUE TITLE
what is wrong

### ISSUE THREAD

**Issue by SchafferApp** [vinivendra/homebrew-gryphon#5]
michael@Mac-mini-von-Michael ~ % brew install vinivendra/gryphon/gryphon
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 6 formulae.
==> New Casks
aethersx2                                  groestlcoin-core                           manila                                     plus42-decimal                             protokol                                   yandex-music-unofficial
ferdium                                    jquake                                     plus42-binary                              podman-desktop                             vieb
==> Updated Casks
Updated 97 casks.

==> Downloading https://rubygems.org/downloads/xcodeproj-1.16.0.gem
Already downloaded: /Users/michael/Library/Caches/Homebrew/downloads/9e7f02841e532e6e0113019acaa6459ebb34d50c4f4f856356ef4d38cfa5e2d4--xcodeproj-1.16.0.gem
==> Downloading https://github.com/vinivendra/Gryphon/archive/v0.18.1.tar.gz
Already downloaded: /Users/michael/Library/Caches/Homebrew/downloads/8b629ab4c4d811f72d9a6169fa3846e116eb5a4879c49493075429d3ad8dddb5--Gryphon-0.18.1.tar.gz
==> Installing gryphon from vinivendra/gryphon
==> Downloading https://rubygems.org/downloads/xcodeproj-1.16.0.gem
Already downloaded: /Users/michael/Library/Caches/Homebrew/downloads/9e7f02841e532e6e0113019acaa6459ebb34d50c4f4f856356ef4d38cfa5e2d4--xcodeproj-1.16.0.gem
==> gem install --install-dir /usr/local/Cellar/gryphon/0.18.1/libexec/vendor /Users/michael/Library/Caches/Homebrew/downloads/9e7f02841e532e6e0113019acaa6459ebb34d50c4f4f856356ef4d38cfa5e2d4--xcodeproj-1.16.0.gem --no-document
==> swift build --disable-sandbox
Last 15 lines from /Users/michael/Library/Logs/Homebrew/gryphon/02.swift:
             ^
/private/tmp/gryphon-20220511-34495-yi78io/Gryphon-0.18.1/Sources/GryphonLib/GryphonSwiftLibrary.swift:590:14: error: unavailable subscript 'subscript(_:)' was used to satisfy a requirement of protocol 'MutableCollection'
public class MutableList<Element>: List<Element>,
             ^
Swift.MutableCollection:8:12: note: 'subscript(_:)' declared here
    public subscript(bounds: Range<Self.Index>) -> Self.SubSequence { get set }
           ^
Swift.MutableCollection:6:14: note: requirement 'subscript(_:)' declared here
    override subscript(bounds: Range<Self.Index>) -> Self.SubSequence { get set }
             ^
[134/139] Compiling GryphonLib AuxiliaryFileContents.swift
[135/139] Compiling GryphonLib Compiler.swift
[136/139] Compiling GryphonLib Driver.swift
[137/139] Compiling GryphonLib Extensions.swift
[138/139] Compiling GryphonLib GryphonAST.swift

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/vinivendra/homebrew-gryphon/issues

These open issues may also help:
Unable to install Gryphon https://github.com/vinivendra/homebrew-gryphon/issues/4

**Comment by rauls4** [comment]
Same issue. Have not been able to find a solution. Fresh install of Xcode 13.4.1.

**Comment by vinivendra** [comment]
Hi @LJ-Mic and @rauls4, this seems to be the same issue as #3, which was fixed in Gryphon version `0.19` with support for Swift 5.6. Please try it out and let me know if it still doesn't work.
